services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
  frontend:
    extends:
      file: ./library-frontend/docker-compose.dev.yml
      service: app
  backend:
    extends:
      file: ./backend/docker-compose.dev.yml
      service: server
  mongo:
    extends:
      file: ./backend/docker-compose.dev.yml
      service: mongo
